# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

# extra settings to be merged into OpenTelemetry Collector configuration
# do not delete this file

## Example configuration for sending data to your own OTLP HTTP backend
## Note: the spanmetrics exporter must be included in the exporters array
## if overriding the traces pipeline.
##

exporters:
  otlphttp/newrelic:
    endpoint: https://otlp.nr-data.net:4318
    headers:
      api-key: YOUR_LICENSE_KEY

service:
  pipelines:
    traces:
      exporters: [otlphttp/newrelic, spanmetrics]
    metrics:
      exporters: [otlphttp/newrelic]
    logs:
      exporters: [otlphttp/newrelic]
